// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dfxsjonrcrlurjpsaome.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmeHNqb25yY3JsdXJqcHNhb21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTczMDgsImV4cCI6MjA3MDY5MzMwOH0.9zySC8u8XVuLlHuHud2oYKalqPd3ZsCCFU_a2dRQ85k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);